### ISSUE TITLE
SerializationException for session-scoped service when reloading session from Redis

### ISSUE THREAD

**Issue by thomasheinen** [jeetmp3/spring-session#12]
It seems like persisting session-scoped services does not work.

I have set up a new Grails 3 project and created a simple controller and a session-scoped service, which stores the current Date in a variable if it is still empty. The controller outputs the content of the Date-variable. I have attached the simple project [grails3-test.zip](https://github.com/jeetmp3/spring-session/files/396739/grails3-test.zip).

When executing the action by calling http://127.0.0.1:8080/hello/index then stopping the Grails-server and restarting the Grails-server, the next call to the action yields the following exception:

ERROR org.grails.web.errors.GrailsExceptionResolver - NotSerializableException occurred when processing request: [GET] /hello/index
reactor.bus.EventBus. Stacktrace follows:
java.lang.reflect.InvocationTargetException: null
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.data.redis.serializer.SerializationException: Cannot serialize; nested exception is org.springframework.core.serializer.support.SerializationFailedException: Failed to serialize object using DefaultSerializer; nested exception is java.io.NotSerializableException: reactor.bus.EventBus
    at grails.artefact.controller.support.ResponseRenderer$Trait$Helper.render(ResponseRenderer.groovy:212)
    at grails3.test.HelloController.index(HelloController.groovy:13)
    ... 3 common frames omitted
Caused by: org.springframework.core.serializer.support.SerializationFailedException: Failed to serialize object using DefaultSerializer; nested exception is java.io.NotSerializableException: reactor.bus.EventBus
    ... 5 common frames omitted
Caused by: java.io.NotSerializableException: reactor.bus.EventBus
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
    at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
    at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
    ... 5 common frames omitted
ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[grailsDispatcherServlet] - Servlet.service() for servlet [grailsDispatcherServlet] in context with path [] threw exception
org.springframework.data.redis.serializer.SerializationException: Cannot serialize; nested exception is org.springframework.core.serializer.support.SerializationFailedException: Failed to serialize object using DefaultSerializer; nested exception is java.io.NotSerializableException: reactor.bus.EventBus
    at org.grails.plugins.springsession.converters.GrailsJdkSerializationRedisSerializer.serialize(GrailsJdkSerializationRedisSerializer.java:33)
    at org.springframework.data.redis.core.AbstractOperations.rawHashValue(AbstractOperations.java:168)
    at org.springframework.data.redis.core.DefaultHashOperations.putAll(DefaultHashOperations.java:129)
    at org.springframework.data.redis.core.DefaultBoundHashOperations.putAll(DefaultBoundHashOperations.java:86)
    at org.springframework.session.data.redis.RedisOperationsSessionRepository$RedisSession.saveDelta(RedisOperationsSessionRepository.java:778)
    at org.springframework.session.data.redis.RedisOperationsSessionRepository$RedisSession.access$000(RedisOperationsSessionRepository.java:670)
    at org.springframework.session.data.redis.RedisOperationsSessionRepository.save(RedisOperationsSessionRepository.java:388)
    at org.springframework.session.data.redis.RedisOperationsSessionRepository.save(RedisOperationsSessionRepository.java:245)
    at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.commitSession(SessionRepositoryFilter.java:244)
    at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.access$100(SessionRepositoryFilter.java:214)
    at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:167)
    at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
    at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:107)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:522)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
    at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:1110)
    at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:785)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1425)
    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.core.serializer.support.SerializationFailedException: Failed to serialize object using DefaultSerializer; nested exception is java.io.NotSerializableException: reactor.bus.EventBus
    at org.springframework.core.serializer.support.SerializingConverter.convert(SerializingConverter.java:68)
    at org.springframework.core.serializer.support.SerializingConverter.convert(SerializingConverter.java:35)
    at org.grails.plugins.springsession.converters.GrailsJdkSerializationRedisSerializer.serialize(GrailsJdkSerializationRedisSerializer.java:31)
    ... 33 common frames omitted
Caused by: java.io.NotSerializableException: reactor.bus.EventBus
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
    at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
    at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
    at org.springframework.core.serializer.DefaultSerializer.serialize(DefaultSerializer.java:46)
    at org.springframework.core.serializer.support.SerializingConverter.convert(SerializingConverter.java:63)
    ... 35 common frames omitted

**Comment by jeetmp3** [comment]
Hi @thomasheinen you're getting this exception because, Grails adds few property in Service class which marked Serializable. The class `reactor.bus.EventBus` in your stacktrace doesn't implements Serializable interface. 

We can use JsonSerializer to solve this kind of issue. Currently it is not configured in plugin we are working on it.

**Comment by thomasheinen** [comment]
Hi @jeetmp3 any update on this? :-)

**Comment by jeetmp3** [comment]
Hi @thomasheinen Sorry I forgot to update you. Yes JsonSupport has been added to newer version of the plugin (doc isn't updated yet :( ). I'll add documentation for the same. You can check the code sample https://github.com/jeetmp3/spring-session-plugin-samples/tree/master/spring-session-redis.
To change serializer to json just add below property in your Config.groovy
```
springsession {
    sessionStore = SessionStore.REDIS
    maxInactiveIntervalInSeconds = 10
    defaultSerializer = Serializer.JDK

redis {
        jackson.modules = ["demo.TestModule"]
    }
}
```
```jackson.modules``` property adds your custom modules. To know more about modules (Jackson Modules) check this https://github.com/FasterXML/jackson-docs/wiki/JacksonMixInAnnotations
