### ISSUE TITLE
Not working with Grails 3.3

### ISSUE THREAD

**Issue by hussainanjar** [jeetmp3/spring-session#21]
It throws following error
```
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.context.embedded.FilterRegistrationBean
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 27 common frames omitted
```

**Comment by bp-FLN** [comment]
@hussainanjar 

you can find a working version for grails 3.3 here: https://github.com/uberall/spring-session/tree/2.0.1-ub

**Comment by hussainanjar** [comment]
@bp-FLN great thanks it works, why don't you get it pushed to grails repo too?

**Comment by bp-FLN** [comment]
the repo is this one: https://bintray.com/uberall/plugins/spring-session/2.0.1-ub

actually i submitted a PR, which got accepted yesterday: https://github.com/jeetmp3/spring-session/pull/22
